services:
  - type: web
    runtime: node
    name: pokescelle
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: EBAY_CLIENT_ID
        sync: false
      - key: EBAY_CLIENT_SECRET
        sync: false
      - key: TOKEN_SECRET
        sync: false
      - key: CRON_SECRET
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
      - key: NODE_ENV
        value: production
